import os

DEFAULT_API_NAME = os.environ.get("API_NAME", "")
DEFAULT_URL_API_GATEWAY = os.environ.get("URL_API_GATEWAY", "")

DEFAULT_KEYCLOAK_HOST = os.environ.get("KEYCLOAK_HOST", "")
DEFAULT_KEYCLOAK_REALM = os.environ.get("KEYCLOAK_REALM", "")
DEFAULT_KEYCLOAK_CLIENT_ID = os.environ.get("KEYCLOAK_CLIENT_ID", "")
DEFAULT_KEYCLOAK_CLIENT_SECRET = os.environ.get("KEYCLOAK_CLIENT_SECRET", "")

DEFAULT_REDIS_HOST = os.environ.get("REDIS_HOST", "")
DEFAULT_REDIS_DB = os.environ.get("REDIS_DB", "")
DEFAULT_REDIS_PORT = os.environ.get("REDIS_PORT", "")
DEFAULT_REDIS_PASSWORD = os.environ.get("REDIS_PASSWORD", "")

DEFAULT_UNPROTECTED_PATH = os.environ.get("UNPROTECTED_PATH", "")
DEFAULT_UNLICENSED_PATH = os.environ.get("UNLICENSED_PATH", "")
